language: python
dist: xenial
sudo: true
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
cache:
  pip: true
  yarn: true
  directories:
    - $HOME/.yarn-cache
    - node_modules
python:
  - "3.6"
  - "3.7"
env:
  - TRAVIS_NODE_VERSION="10.5"
before_install:
  - sh -e /etc/init.d/xvfb start
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn global add @angular/cli
  - ng --version
install:
  - pip install --upgrade setuptools pip
  - pip install --upgrade --requirement requirements/development.txt
  - pip install --upgrade .[big_mode]
  - pip freeze
  - cd client && npm install && cd ..
script:
  - flake8 openslides tests
  - isort --check-only --diff --recursive openslides tests
  - python -m mypy openslides/
  - pytest --cov --cov-fail-under=70
  - cd client && npm run-script lint && cd ..
  - cd client && ng test --watch=false && cd ..
