# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-21 20:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import openslides.utils.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('motions', '0002_motion_origin'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotionChangeRecommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveIntegerField()),
                ('status', models.PositiveIntegerField(default=0)),
                ('line_from', models.PositiveIntegerField()),
                ('line_to', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('creation_time', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('motion_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_recommendations', to='motions.MotionVersion')),
            ],
            options={
                'default_permissions': (),
            },
            bases=(openslides.utils.models.RESTModelMixin, models.Model),
        ),
    ]
