# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-08 19:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motions', '0004_auto_20160907_2343'),
        ('motions', '0003_motionchangerecommendation'),
    ]

    operations = [
    ]
