# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motions', '0005_motionchangerecommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motionchangerecommendation',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
