# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-30 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motions', '0007_motionversion_first_line_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motionversion',
            name='first_line_number',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
